# Generated by Django 3.1 on 2021-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_variationmanager'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variantions',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
