# Generated by Django 3.1 on 2021-09-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variantions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variantions',
            new_name='variations',
        ),
    ]
